services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snackshop
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/docker/init:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/snackshop'
    depends_on:
      - db
    working_dir: /app/server
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres-data:
